INSERT INTO ROLES(ROLE) VALUES ('ADMIN')
INSERT INTO ROLES(ROLE) VALUES ('USER')

--password = abcd
INSERT INTO USERS(USERNAME, ENCODED_PASSWORD, ACTIVE) VALUES ('sda_admin', '$2a$10$IMBxLyBLqJyx4Pfl/lRSYOOtat/g/V.aw6tKaXQ2Nv4jIjL0pgBVi', 1)
INSERT INTO USERS(USERNAME, ENCODED_PASSWORD, ACTIVE) VALUES ('sda_user', '$2a$10$IMBxLyBLqJyx4Pfl/lRSYOOtat/g/V.aw6tKaXQ2Nv4jIjL0pgBVi', 1)

INSERT INTO USERS_ROLES VALUES (1,1)
INSERT INTO USERS_ROLES VALUES (2,2)